### ISSUE TITLE
probably a code error?

### ISSUE THREAD

**Issue by SchlauFuchs** [jodconverter/jodconverter-samples#10]
https://github.com/jodconverter/jodconverter-samples/blob/31f2d72d1a4e81f0f5941747ae5f2038315057f8/samples/spring-boot-rest/src/main/java/org/jodconverter/sample/rest/ConverterController.java#L139

If I understand the code correctly the rest controller is supposed to move the input parameters into load and store parameters depending on the prefixes defined. The method #addProperty(String, String, Map.Entry, Map) is filtering and then the line above in #addProperty(String, Map.Entry, Map) is supposed to derive the name from that property and add the k/v pair into the provided map. There are two bugs here, one is that not the prefix is handed in but the parameter name, and then the name is calculated from the substring of the property name beginning at the property name length, leading to an empty string as name.

**Comment by kemuning** [comment]
Hi, did you manage to run the sample code ? No error message like I have [here](https://github.com/jodconverter/jodconverter/issues/344) ?

**Comment by sbraconnier** [comment]
Sorry I took so long to fix this. It is fixed now.
