### ISSUE TITLE
Feature: add smoke tests

### ISSUE THREAD

**Issue by EugenMayer** [jodconverter/jodconverter-samples#3]
we should add smoke tests so we now the examples are actually working. We should run those via the CI (as before)

**Comment by sbraconnier** [comment]
I agree. I'll see if I can make you a member of the cirrus-ci management.

**Comment by EugenMayer** [comment]
well i could do that in github using workflows too. Maybe for the example project that's not a bad option?

**Comment by sbraconnier** [comment]
Sure thing!! Feel free to do it :).

**Comment by EugenMayer** [comment]
Nice, will do.

Finished moving the docker example project to this repo and just release it https://github.com/jodconverter/docker-image-jodconverter-examples/releases/tag/4.4.5-5 - so we are aligned.

**Comment by sbraconnier** [comment]
Didn't know about github workflow! This is nice!

I'm not sure why the build fails, so I'll let you deal with it :)
