### ISSUE TITLE
Add more top-level docs

### ISSUE THREAD

**Issue by EugenMayer** [jodconverter/jodconverter-samples#4]
So both, adding docs on how to compile the projects 

```
./gradlew -x test :samples:spring-boot-webapp:build
./gradlew -x test :samples:spring-boot-rest
```

or maybe just move the readme from https://github.com/jodconverter/jodconverter-samples/tree/main/samples to top level. I would find it more appealing to the one exploring finding the index on the topmost level

And how to quick run them using docker.

rest with GUI
```bash
docker run --rm -p 8080:8080 ghcr.io/jodconverter/jodconverter-examples:gui
```

rest only
```bash
docker run --rm -p 8080:8080 ghcr.io/jodconverter/jodconverter-examples:rest
```

I would suggest linking the https://github.com/jodconverter/docker-image-jodconverter-examples repository as a "running example" here, maybe even borrowing some of the quick start examples like

@sbraconnier what do you think?

**Comment by sbraconnier** [comment]
I agree! Documentation is not my strong suite. This is what I want to focus on (for the main project) now that the project has moved to an organization. Feel free to do whatever you want about it here! (And even the main project if you have ideas).

**Comment by EugenMayer** [comment]
Thanks for the heads up. I went bold and took a first shot. I would say, since this is just the example project, we should keep it simple and loose. If you like, just throw your thoughts on it, improve or whatever.

If we feel like coordinating that effort better, one of us will surely open an issue and do so. 

Thank you for listening :)
