### ISSUE TITLE
Centralize the dependencies version management

### ISSUE THREAD

**Issue by sbraconnier** [jodconverter/jodconverter-samples#6]
In order for us to be able to "bulk upgrade" the samples dependencies, there should be a central point where versions could be configured, and it must remain optional to use them.

**Comment by sbraconnier** [comment]
Fixed by [this commit](https://github.com/jodconverter/jodconverter-samples/commit/38e9564f58827769b674530ce0c8623631ff8732)

**Comment by EugenMayer** [comment]
You should have a look / glimps at gradle version catalogs :) IMHO they are more suitable for what you are doing with a build-convention plugin in this case (AFAICS). 

But what works, works :)
