### ISSUE TITLE
application.properties

### ISSUE THREAD

**Issue by carcuevas** [jodconverter/jodconverter-samples#8]
Hello, 

where I can find a list of options for writing a config in `application.properties` or some more extended example...   I tried to find it something in this repo, but no luck...  

thanks a lot guys :)

**Comment by carcuevas** [comment]
ohghh my head... I Found it  finally: 

https://github.com/jodconverter/jodconverter/wiki/Configuration

**Comment by carcuevas** [comment]
sorry for that guys

**Comment by sbraconnier** [comment]
@carcuevas For a list of all the properties you can set in a spring-boot app, take a look [here](https://github.com/jodconverter/jodconverter/blob/master/jodconverter-spring-boot-starter/src/integTest/resources/config/application-props.properties). It is a config file used for a test. Not ideal but at least you have the complete list. It should be documented somewhere...

**Comment by carcuevas** [comment]
Ohh perfect thanks very much :-)))
